### ISSUE TITLE
City field in the new school registration page can be made disable unless a state is selected from the dropdown

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#10]
Log on into the application as a OUP Admin and go to the new school registration page → address details section →  Can we keep the city field in disable form unless and until a state is selected.

**Comment by supriti-mukherjee** [comment]
It is not required as per the requirements.

**Comment by summar1** [comment]
OUP Requirement

**Comment by summar1** [comment]
OUP Requirement
