### ISSUE TITLE
School Admin--> Classes--> Replace teacher--> Do a blank search, then select a class and do the search, now click on reset, the value in the class dropdown  and section is not getting reset.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#100]
School Admin--> Classes--> Replace teacher--> Do a blank search, then select a class and do the search, now click on reset, the value in the class dropdown
 and section is not getting reset.

**Comment by supriti-mukherjee** [comment]
Fixed and will be reflected in next deployment

**Comment by summar1** [comment]
ok
