### ISSUE TITLE
School Admin--> Create new teacher--> Pincod is shown as non mandatory field yet while saving teacher record keeping pincode blank, the field is  highlighted in red. "*" needs to be provided against pincode field

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#101]
School Admin--> Create new teacher--> Pincod is shown as non mandatory field yet while saving teacher record keeping pincode blank, the field is 
highlighted in red. "*" needs to be provided against pincode field

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
