### ISSUE TITLE
School Admin--> Utilities--. Whithout selecting any value click on the export selected or print welcome letter link at the top, In the information the "No" button can be removed

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#102]
School Admin--> Utilities--. Whithout selecting any value click on the export selected or print welcome letter link at the top, In the information the "No" button
can be removed

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
