### ISSUE TITLE
If class is selected then without selecting any section user should be able to view students in the select student dropdown

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#104]
As per FSD if the teacher has sent a notification to selected students of a section, then in the grid the section should show as (..) and when user clicks on it the pop up should show student name, class and section but currently only student name is showing. Same has to be applied for Class column which means, when a class is selected from the drop down and section is not selected then in select student all the student of that class should be displayed

**Comment by mouparnadas** [comment]
Please provide the steps to replicate. This can be an enhancement request.

**Comment by supriti-mukherjee** [comment]
Fixed and working as per the requirements.
