### ISSUE TITLE
 When teacher is trying to update their profile then even if the Gender field is left blank, neither a message is displayed nor the field is highlighted in red. Also if user tries to do a blank save, gender field is not getting highlighted.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#107]
When teacher is trying to update their profile then even if the Gender field is left blank, neither a message is displayed nor the field is highlighted
in red. Also if user tries to do a blank save, gender field is not getting highlighted.

**Comment by supriti-mukherjee** [comment]
Duplicate bug. To be fixed.
