### ISSUE TITLE
Mismatch in sections

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#110]
Log on into the application as Teacher and click on create notification. If a teacher is assigned to only one secrtion lets say section B of Class 3. Then select class and without selecting any section fill other details and click on send/schedule. In the notification history grid, section column is showing the section of the teacher I.e “B”. Click on the edit icon to view the notification details. There the section column is shown as “select section”

**Comment by supriti-mukherjee** [comment]
Fixed and can be seen in next deployment

**Comment by summar1** [comment]
Not fixed. Issue still persists.

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
