### ISSUE TITLE
Invalid error message thrown

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#112]
Log on into the application as teacher and click on classes. Click on the assign Task link. Fill all the details and click on assign. Invalid error message is thrown
![1](https://cloud.githubusercontent.com/assets/16289032/12552130/c4b6332a-c395-11e5-8546-21fef84737f1.jpg)

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
