### ISSUE TITLE
Teacher/ Student is receiving same mail more than 2 – 3 times

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#113]
Log on into the application as OUP and min and try to do a bulk upload for students and teachers. Against one student provide a mail id and against all the teacher provide same mail id. When the data is uploaded, for student 2- 3 mails are received in the mail box and for different teacher only one mail multiple time with same credential and salutation is received

**Comment by supriti-mukherjee** [comment]
closed
