### ISSUE TITLE
1. log on ionto the application as teacher and assign a task. Now go to search task and do a seach based on class or start date. data is not shown.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#114]
log on ionto the application as teacher and assign a task. Now go to search task and do a seach based on class or start date. data is not shown.

**Comment by manasghosh81** [comment]
This is fixed. The search is now working.

**Comment by supriti-mukherjee** [comment]
Not fixed

**Comment by supriti-mukherjee** [comment]
Create a task-> Task is successfully created-> Go to search task-> Give the start date and search-> Task results are displayed->Click on reset-> Select a class and search-> No data found is displyayed

**Comment by supriti-mukherjee** [comment]
Fixed
