### ISSUE TITLE
log on ionto the application as teacher and search for a task. Click on the edit icon. It is taking the user to edit task page but it is not working as  desired

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#115]
log on ionto the application as teacher and search for a task. Click on the edit icon. It is taking the user to edit task page but it is not working as 
desired

**Comment by manasghosh81** [comment]
As per FSD on edit task page the user can edit student assignment. This is working.

**Comment by summar1** [comment]
working now
