### ISSUE TITLE
Log on into the application as OUP admin and try to do a bulk upload for a teacher.Here there is a mismatch in the password generated in DB and the password sent to the user via mail. Also for 1st login using password shared via mail, the secret question drop down is not showing any questions.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#116]
Log on into the application as OUP admin and try to do a bulk upload for a teacher.Here there is a mismatch in the password generated in DB and the
password sent to the user via mail. Also for 1st login using password shared via mail, the secret question drop down is not showing any questions.

**Comment by supriti-mukherjee** [comment]
Fixed and can be checked in next deployment

**Comment by summar1** [comment]
Working now
