### ISSUE TITLE
Log on into the application as school admin and go to classes. Click on create new teacher and fill all the details and click on create. There is a mis match in the password generated in DB and the password sent to the user via mail.And user is not able to log on into the application with both the  passwords

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#117]
Log on into the application as school admin and go to classes. Click on create new teacher and fill all the details and click on create. There is a mis
match in the password generated in DB and the password sent to the user via mail.And user is not able to log on into the application with both the 
passwords

**Comment by supriti-mukherjee** [comment]
Fixed and can be checked in next deployment.

**Comment by manasghosh81** [comment]
The functionality is working correctly.
Please retest.

**Comment by supriti-mukherjee** [comment]
Fixed
