### ISSUE TITLE
All the mandatory fields border should get highlighted in red for a blank save

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#12]
Log on into the application as a OUP Admin and go to the new school registration page. Keeping all the mandatory fields blank, 
   click on the save button. All the field borders are highlighted in red except school name which is highlighted in blue and 
drop down fields country state and gender which is not highlighted at all
![blank highlight](https://cloud.githubusercontent.com/assets/16289032/11925014/1a417b3a-a7dd-11e5-93e3-e23991c18c28.jpg)

**Comment by supriti-mukherjee** [comment]
Since the cursor is present in School name field, it is not highlighted in red. So it is not an issue.
Highlighting dropdowns in red is implemented.

**Comment by summar1** [comment]
Fixed now
