### ISSUE TITLE
school admin not able to create teacher

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#120]
Log on into the application as school admin and click on classes. Select the create new teacher and fill all the required details and click on save. The message says "Teacher has not been created. Please contact the support team"
![error](https://cloud.githubusercontent.com/assets/16289032/12748959/964ed5a2-c9d3-11e5-9b6b-58d13fd68301.jpg)

**Comment by manasghosh81** [comment]
This had been a mail server issue. Rechecked and the functionality is working fine.
Please retest.

**Comment by summar1** [comment]
Working fine
