### ISSUE TITLE
Advance search not working for teachers created by school admin who are not assigned to any class or section

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#122]
Log on into the application as a School admin and click on classes. Click on create new teacher and create a teacher. Log on into the application with this new created teacher and click on advance search. User is taken to error page.

**Comment by manasghosh81** [comment]
This issue has been fixed and deployed to QA. Please review.

**Comment by supriti-mukherjee** [comment]
Fixed and closing on behalf of Sonia
