### ISSUE TITLE
Scroll bar needs to be provided for assign resource of  Resources

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#123]
Scroll bar needs to be provided for assign resource of  Resources
![scroll](https://cloud.githubusercontent.com/assets/16289032/12780143/19ce7450-ca92-11e5-9e9a-6f579068ff8c.jpg)

**Comment by manasghosh81** [comment]
The scroll bar has been provided on the resource selection page.

**Comment by supriti-mukherjee** [comment]
Fixed. Closing on behalf of Sonia.

**Comment by supriti-mukherjee** [comment]
It is partially fixed.

**Comment by summar1** [comment]
Fixed now
