### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#129]
Go to Resource page from Teacher login-> Change class from dropdown->1st topic is not auto-highlighted->Resources are not getting populated. User has to select a particular topic to view the resources

![image6](https://cloud.githubusercontent.com/assets/11663550/12839948/2d0fe79c-cc04-11e5-8dd2-566fc128f798.PNG)

**Comment by mouparnadas** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Fixed
