### ISSUE TITLE
In “Administrator detail section” of New school register, the email id field is taking duplicate value and saving the data

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#13]
Log on to the application as OUP Admin. Go to new school registration. Provide all the mandatory details and 
 In the "Administrator details section", in the email address field try to provide an already existing email in the
application and click on save. The school is getting created successfully. This should not happen as no two person can have same email address. Instead a pop up message giving the warning as " email id already exists" should be thrown.

**Comment by supriti-mukherjee** [comment]
Emails can be duplicate. Not an issue

**Comment by summar1** [comment]
ok
