### ISSUE TITLE
UI defect

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#140]
Direction of arrow is not proper
![image8](https://cloud.githubusercontent.com/assets/11663550/12845091/843f96c8-cc29-11e5-8e49-94c250d4d073.PNG)

**Comment by OUPGandhinagar** [comment]
We need to spend some time to resolved it..will try complete in next deployment.

**Comment by OUPGandhinagar** [comment]
Done in Local. Checked in SVN.

**Comment by supriti-mukherjee** [comment]
Fixed
