### ISSUE TITLE
Spelling Issue

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#144]
Spelling of 'Testimonial' should be 'Testimonials' 
![image10](https://cloud.githubusercontent.com/assets/11663550/12879641/39bf8c0e-ce5c-11e5-9bf7-d080556e2807.PNG)

**Comment by OUPGandhinagar** [comment]
Done in Local

**Comment by supriti-mukherjee** [comment]
Fixed
