### ISSUE TITLE
UI Defect Spacing Issue

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#146]
Text and textbox distance is not uniform for 'Input Symbols' 

![image11](https://cloud.githubusercontent.com/assets/11663550/12879660/9123be48-ce5c-11e5-829c-b2171ea8d9e1.PNG)

**Comment by OUPGandhinagar** [comment]
Done in Local

**Comment by supriti-mukherjee** [comment]
Fixed.
