### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#148]
Contact number field is taking more than 10 characters and the form is getting submitted. Contact number validation is not working.

**Comment by mouparnadas** [comment]
This has been fixed and will be available in next deployment

**Comment by supriti-mukherjee** [comment]
Not Fixed.

**Comment by mouparnadas** [comment]
Fixed. As per requirement only 10 digits are allowed

**Comment by supriti-mukherjee** [comment]
Fixed
