### ISSUE TITLE
“About” link on the home screens can be changed to “About Us”

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#15]
As per the FSD “About” link on the home screens can be changed to “About Us”
![about](https://cloud.githubusercontent.com/assets/16289032/11929986/95adcc92-a805-11e5-8f77-65ce140c1c10.jpg)

**Comment by supriti-mukherjee** [comment]
Implemented

**Comment by summar1** [comment]
working now

**Comment by summar1** [comment]
Arising again

**Comment by OUPGandhinagar** [comment]
Done in local & committed in SVN

**Comment by supriti-mukherjee** [comment]
Discussed with customer--- "About" is correct
