### ISSUE TITLE
Teacher grid is showing Teacher who is not attached to any class or section

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#154]
Log on into the application as OUP Admin and create a new school. Upload students and Teachers to the School. Search the school and click on edit icon. In the edit screen update all the dates (academic start end and subscription start end date ) and click on save. It will throw an error message whether user wants to proceed with new subscription or want to update the dates. Select for new subscription. Now go to advance search, select the school and click search. No data is available. The students and Teacher grid should show the details in deactivated form. Teacher grid is showing Teacher who is not attached to any class or section

**Comment by mouparnadas** [comment]
Fixed

**Comment by summar1** [comment]
Fixed now
