### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#156]
Log on into the application as OUP Admin and create a new school. Seach the school and update its academic start/end date. User is able to save the data
successfully even if the academic start date and end date is greater then subscription start date and end date
![dates](https://cloud.githubusercontent.com/assets/16289032/12886796/f1bbf98a-ce95-11e5-94d3-693efa63a58e.jpg)

**Comment by mouparnadas** [comment]
The issue has been fixed and will be available in next deployment.

**Comment by mouparnadas** [comment]
Fixed

**Comment by summar1** [comment]
fixed now
