### ISSUE TITLE
Highlighted fields

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#157]
Log on into the application as OUP admin and click on School Register. Fill some mandatory data and keep other mandatory data like class code, subscription
and School Admin details and clic on Register. The Mandatory fields are getting highlighted in Red. Now start filling the fields, those are still highlighted 
in Red and if the user click on the "+" button of the class/subscription the new textbox and dropdown is also highlighted in red

**Comment by supriti-mukherjee** [comment]
Not a defect
