### ISSUE TITLE
On the home screen, a field as “Board” should be made available and against it the dropdown field to select the board should be present with CBSE as a prepopulated value and should be non editable

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#16]
As per the FSD, On the home screen, a field as “Board” should be made available and against it the dropdown field to select the board should be present with CBSE as a prepopulated value and should be non editable
![board](https://cloud.githubusercontent.com/assets/16289032/11930002/c24a854c-a805-11e5-8e68-edee126f17a4.jpg)

**Comment by supriti-mukherjee** [comment]
The non-editable dropdown is there but it is overlapped by the "Oxford Maths" icon. Need to reduce the height of the icon.

**Comment by summar1** [comment]
As discussed with the dev team it will remain as such as of now
