### ISSUE TITLE
Bulk Upload Issue

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#162]
Status is showing 'No errors'  but action is showing 'Failed' after clicking on upload.

**Comment by mouparnadas** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
unable to test it as status is showing 'errors present'

**Comment by pankaj44** [comment]
fixed

**Comment by supriti-mukherjee** [comment]
Fixed
