### ISSUE TITLE
Student Performance Report

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#167]
Text should contain "'s" in the heading .
![image13](https://cloud.githubusercontent.com/assets/11663550/12888888/31c6b5f4-cea2-11e5-91be-a11b23498d12.PNG)

**Comment by mouparnadas** [comment]
This has been fixed and will be available in next deployment.

**Comment by supriti-mukherjee** [comment]
Fixed
