### ISSUE TITLE
If a class- section combination contains two or more student having same name, then data is not getting upload.   (duplicatestudent.jpg)

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#17]
Log on into the application as OUP Admin and Click on the school search. Select a school and click on the upload button from the Action column. Try to upload a sheet which contains same student name for a class- section combination . Click on validate. An error log is generated which says duplicate student name
![er](https://cloud.githubusercontent.com/assets/16289032/11954563/b2e00486-a8cf-11e5-983b-83e169c2e1f2.jpg)

**Comment by supriti-mukherjee** [comment]
Please check it once. If a single class-section has 3 students with same name but different roll numbers, then the students are getting created but with warnings. This is the exact logic.

**Comment by summar1** [comment]
working now
