### ISSUE TITLE
Tooltip issue

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#178]
Login as School Admin -> Classes -> Select class from dropdown -> Click Go -> Click on View Student icon under action column -> Student list will open up -> Tooltip is not present under action column for the student table

**Comment by mouparnadas** [comment]
This tooltip is not present in any of the tables. Each action tool tip is present. this is not a bug

**Comment by supriti-mukherjee** [comment]
Fixed
