### ISSUE TITLE
If the roll no of the students is same for the same class-section combination, then in the error sheet its  showing as "Duplicate Name...". It should show "Duplicate Roll number"

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#18]
If the roll no of the students is same for the same class-section combination, then in the error sheet its 
showing as "Duplicate Name...". It should show "Duplicate Roll number"
![duplicate](https://cloud.githubusercontent.com/assets/16289032/11954582/cfe6c808-a8cf-11e5-9126-52bf82c06809.jpg)

**Comment by supriti-mukherjee** [comment]
It is fixed. It will be available in the deployment.

**Comment by summar1** [comment]
Fixed now
