### ISSUE TITLE
The upload detail grid should show the result uploaded for the particular school and not the whole upload.  

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#19]
The upload detail grid should show the result uploaded for the particular school and not the whole upload.
  If a user uploads the detail from one school and then tries to upload the details for other school then the upload
grid for the second school should be blank instaed of populating data of 1st school

**Comment by supriti-mukherjee** [comment]
It is not a defect because the upload details page can be seen by OUP admin only but not by the users

**Comment by summar1** [comment]
Requirement
