### ISSUE TITLE
Drop down button can be changed to a solid down arrow button

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#2]
Log on into the application as OUP Admin. Click on the register school link. In the register new school page the UI of the drop down buttons i.e the down arrow can be changed to a solid down arrow. It will look more good. 
Refer to the screenshot - 
![dropdown](https://cloud.githubusercontent.com/assets/16289032/11924781/09151c10-a7db-11e5-8a72-4c45b7a58a5b.jpg)
dropdown.jpg

**Comment by supriti-mukherjee** [comment]
Its not an issue as per UI expert.

**Comment by summar1** [comment]
ok
