### ISSUE TITLE
Log on into the application as OUP Admin. Search a school and click on upload button. Browse the file from and validate it. Once a file is error free    an "up arrow" is available under the "action" column to upload the detail. Click on the button. Its taking more than 15 minutes to process.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#20]
Log on into the application as OUP Admin. Search a school and click on upload button. Browse the file from and validate it. Once a file is error free
   an "up arrow" is available under the "action" column to upload the detail. Click on the button. Its taking more than 15 minutes to process.

**Comment by supriti-mukherjee** [comment]
It is fixed now. Please check it once.

**Comment by summar1** [comment]
working now
