### ISSUE TITLE
Home Page links

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#202]
Sequence of the links is not as per the FSD

![image20](https://cloud.githubusercontent.com/assets/11663550/12944290/2b27957c-d00c-11e5-87dc-f1e395ce1299.PNG)

![image21](https://cloud.githubusercontent.com/assets/11663550/12944295/32020c92-d00c-11e5-9537-030c2fefb0c1.PNG)

**Comment by OUPGandhinagar** [comment]
@supriti-mukherjee 

This sequence is as per design approved by client.

**Comment by supriti-mukherjee** [comment]
Closed
