### ISSUE TITLE
Log on into the application as OUP Admin. Search a school and click on upload button. Browse the file from and validate it. Once a file is error free    an "up arrow" is available under the "action" column to upload the detail. Click on the button and without waiting for it to be processed leave the page    Again visit the same page, there is no option available for the upload and user is not able to know whether the details has been uploaded successfully or not    (upload.jpg)

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#21]
Log on into the application as OUP Admin. Search a school and click on upload button. Browse the file from and validate it. Once a file is error free
   an "up arrow" is available under the "action" column to upload the detail. Click on the button and without waiting for it to be processed leave the page
   Again visit the same page, there is no option available for the upload and user is not able to know whether the details has been uploaded successfully or not
   (upload.jpg)
![upload](https://cloud.githubusercontent.com/assets/16289032/11992012/af0fb8a6-aa46-11e5-8e99-5abc8bdacdbb.jpg)

**Comment by supriti-mukherjee** [comment]
It is fixed.

**Comment by summar1** [comment]
working now
