### ISSUE TITLE
School Admin Advance Search

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#216]
Login as School Admin -> Perform some search -> close the collapsible grids by clicking on the arrows -> now again perform some search -> the collapsible grids are not opening with the results

**Comment by mouparnadas** [comment]
This is working fine.

**Comment by supriti-mukherjee** [comment]
Not fixed.

**Comment by supriti-mukherjee** [comment]
![image33](https://cloud.githubusercontent.com/assets/11663550/12993116/5effe970-d13e-11e5-9d82-0a36838908d1.PNG)

**Comment by supriti-mukherjee** [comment]
Fixed
