### ISSUE TITLE
Create Notification by School Admin

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#218]
Create notification for both teachers and students of a class-section in which student is not present -> Notification is created and sent successfully without giving any error -> In the recipient list Student is not shown. But error message should be thrown stating that students are not associated with the class-section

**Comment by manasghosh81** [comment]
As discussed with Subha da, It is not a defect.

**Comment by supriti-mukherjee** [comment]
closed
