### ISSUE TITLE
All the mandatory fields border should get highlighted in red for a blank save

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#22]
Log on into the application as a OUP Admin and go to the new school registration page. Keeping all the mandatory fields blank, 
   click on the save button. All the field borders are highlighted in red except 
drop down fields country, state, class code and suscription count which is not highlighted at all
![highlightred](https://cloud.githubusercontent.com/assets/16289032/12049840/b92e1406-af12-11e5-8ed8-d63879c3a8a8.jpg)

**Comment by supriti-mukherjee** [comment]
It is fixed now.

**Comment by summar1** [comment]
Fixed now
