### ISSUE TITLE
Abrupt error message thrown

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#23]
Log-on into the application as OUP admin and click on the OUP Admin profile link at the right top corner. User is redirected to the OUP Admin Profile page. Keeping The Gender field as blank try to save  the data. Instead of showing a warning message to fill the gender field, user is redirected to a screen with weird and abrupt error message
![erroronsave](https://cloud.githubusercontent.com/assets/16289032/12049852/d5406072-af12-11e5-868d-231356325b9b.jpg)

**Comment by supriti-mukherjee** [comment]
Application is not allowing the user to save data without entering the gender. No abrupt error message is thrown at our end. Please check it once.

**Comment by summar1** [comment]
Now user is not allowed to save data, but the field should get highlighted in red if it is left blank and user tries to update or save

**Comment by supriti-mukherjee** [comment]
Fixed.

**Comment by summar1** [comment]
Fixed
