### ISSUE TITLE
 Log on into the application as OUP Admin and click on register school. Keep all the fields blank and click on register. All the mandatory fields are highlighted in red. Now just give the school name and click on register. The academic session start calaender is automatically opened

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#233]
Log on into the application as OUP Admin and click on register school. Keep all the fields blank and click on register. All the mandatory
fields are highlighted in red. Now just give the school name and click on register. The academic session start calaender is automatically opened

**Comment by mouparnadas** [comment]
The control moves on the very first blank field of the application. If you enter the first date and click save the next calender will open. This is how the code works.

**Comment by manasghosh81** [comment]
Invalid

**Comment by supriti-mukherjee** [comment]
closed
