### ISSUE TITLE
Log and click on reset. Contact no for school admin is not getting reset. Also if the user has selected 2 - 3 class and subscription then that no of text boxes are visible for class wise subscription details Field

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#234]
1.Log on into the application as OUPADMIN and go to school register.
2.Fill all the mandatory field and click on reset. Contact no for school admin is not getting reset. 
3.Also if the user has selected 2 - 3 class and subscription then that no of text boxes are visible for class wise subscription details part

**Comment by mouparnadas** [comment]
Cannot replicate

**Comment by summar1** [comment]
1.Log on into the application as OUPADMIN and go to school register.
2.Fill all the mandatory field and click on reset. Contact no for school admin is not getting reset. 
3.Also if the user has selected 2 - 3 class and subscription then that no of text boxes are visible for class wise subscription details part

**Comment by supriti-mukherjee** [comment]
Fixed
