### ISSUE TITLE
User name is showing User's First name

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#24]
Log on into the application as School Admin or OUP Admin and click on My profile. The User name field is showing User's first name. It should show the login id
![username](https://cloud.githubusercontent.com/assets/16289032/12049860/f7387dcc-af12-11e5-83f5-d43da665fab8.jpg)

**Comment by supriti-mukherjee** [comment]
Correct implementation has been done.

**Comment by summar1** [comment]
Fixed now
