### ISSUE TITLE
Log on into the application as teacher and click on report--> class performance report--> select class as "class8" in section only two section is shown  as "A" & "L". select a section and click on search. Now again click on the section dropdown. one additional section as "TT" is available

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#244]
Log on into the application as teacher and click on report--> class performance report--> select class as "class8" in section only two section is shown
 as "A" & "L". select a section and click on search. Now again click on the section dropdown. one additional section as "TT" is available

**Comment by supriti-mukherjee** [comment]
Fixed
