### ISSUE TITLE
School Admin--> classes-> student transfer--> "!" should be available in the confirmation message instead of"." and the "cancel" button  should be removed. Same for Teacher replace, No punctuation available in the confirmation message.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#246]
School Admin--> classes-> student transfer--> "!" should be available in the confirmation message instead of"." and the "cancel" button 
should be removed. Same for Teacher replace, No punctuation available in the confirmation message.

**Comment by mouparnadas** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Fixed
