### ISSUE TITLE
School Admin--> classes-> student transfer--> When user is doing a single transfer then the "student in class section:..." remains on the screen, but when user is doing a bulk transfer then the "student in class section:..." is getting closed

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#247]
School Admin--> classes-> student transfer--> When user is doing a single transfer then the "student in class section:..." remains on the screen,
but when user is doing a bulk transfer then the "student in class section:..." is getting closed

**Comment by pankaj44** [comment]
Not a defect

**Comment by supriti-mukherjee** [comment]
closed
