### ISSUE TITLE
search school and utilities by oupadmin

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#249]
no tooltip on search and reset button in utilities and search school while there is a tooltip for register and reset button in register school

![8](https://cloud.githubusercontent.com/assets/11663550/12971028/15af2c22-d0bc-11e5-8a4d-1f8517182b0e.png)

**Comment by manasghosh81** [comment]
Deffered

**Comment by supriti-mukherjee** [comment]
closed
