### ISSUE TITLE
side key panel of school admin

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#255]
no tooltip on reports. Tooltip is present only on icon. where tooltip is present on both icons and letters everywhere

![14](https://cloud.githubusercontent.com/assets/11663550/12971230/b81ae396-d0be-11e5-8caa-9c707c629bc4.png)

**Comment by mouparnadas** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Fixed
