### ISSUE TITLE
A one liner can be provided at the bottom of profile pic to let the user know what file type can be uploaded and upto what size

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#26]
A one liner can be provided at the bottom of profile pic to let the user know what file type can be uploaded and upto what size

**Comment by supriti-mukherjee** [comment]
Done

**Comment by summar1** [comment]
This should be implemented in all the screens which has got image upload feature

**Comment by mouparnadas** [comment]
Implemented. Please test.

**Comment by supriti-mukherjee** [comment]
fixed
