### ISSUE TITLE
Punctuation issue

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#261]
Teacher -> Reports -> Task Status -> Select Class,Section and chapter

![defect27](https://cloud.githubusercontent.com/assets/11663550/12971869/d203c708-d0c5-11e5-9f09-fe8da9c6f816.PNG)

**Comment by mouparnadas** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
fixed
