### ISSUE TITLE
student home page

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#269]
Lesson and Homework appears on tile on top of another, should be side by side for student dashboard.

![capture](https://cloud.githubusercontent.com/assets/11663550/12972970/794569d2-d0cf-11e5-976b-480235ddff6b.PNG)

**Comment by OUPGandhinagar** [comment]
Done in Local..

**Comment by supriti-mukherjee** [comment]
Fixed
