### ISSUE TITLE
Bulk upload is not working properly

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#27]
Log on into the application as OUP Admin and create a school. Now search the school and try to bulk upload the student and teacher details. It is not working as desired and even if the sheet does not have any error, in the action column the status is shown as Failed. And when user does an advance search then partiallyu created data is shown
![check1](https://cloud.githubusercontent.com/assets/16289032/12113436/b0d3f176-b3c8-11e5-95bc-ab620c247701.jpg)
![check2](https://cloud.githubusercontent.com/assets/16289032/12113443/b9860890-b3c8-11e5-974c-5ce4f386603d.jpg)

**Comment by supriti-mukherjee** [comment]
Its working now. please check it once.

**Comment by summar1** [comment]
Not working as desired in my end

**Comment by summar1** [comment]
Fixed
