### ISSUE TITLE
oxford maths home page

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#277]
clicking on "learn more" of student when the pop up appears, the alignment is not correct.

![untitled](https://cloud.githubusercontent.com/assets/11663550/12973973/77f22faa-d0d6-11e5-8d5e-8a52bfa6566f.png)

**Comment by mouparnadas** [comment]
Non issue confirmed from business

**Comment by supriti-mukherjee** [comment]
closed
