### ISSUE TITLE
All data is not getting created

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#28]
Log on into the application as OUP Admin and create a school. Now search the school and try to bulk upload the student and teacher details. In the Advance search screen, select the school from dropdown and click on search. All the records in the sheet are not getting created and only partial data is shown

**Comment by supriti-mukherjee** [comment]
It is fixed. Please check it once.

**Comment by summar1** [comment]
Not working as desired in my end

**Comment by summar1** [comment]
Fixed
