### ISSUE TITLE
School Admin--> Utilities--> is a combination or search criteria does not contains teacher details, then "No data found" message which is thrown is not  aligned as other screens.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#281]
School Admin--> Utilities--> is a combination or search criteria does not contains teacher details, then "No data found" message which is thrown is not
 aligned as other screens.

**Comment by pankaj44** [comment]
after deployment in QA

**Comment by summar1** [comment]
fixed now
