### ISSUE TITLE
Teacher--> search task--. select only class from dropdown and click on search, no data is shown how ever when user selects the section then the created  task is shown. Samratsharma/S@nia2016

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#283]
Teacher--> search task--. select only class from dropdown and click on search, no data is shown how ever when user selects the section then the created 
task is shown. Samratsharma/S@nia2016

**Comment by summar1** [comment]
This issue is occurring for one particular user.

**Comment by pankaj44** [comment]
not able to reproduce.

**Comment by supriti-mukherjee** [comment]
it may be a data issue
