### ISSUE TITLE
 Teacher--> Resources--> class 8--> select 05 "playing with numbers". It has topic and games. Click on view game dropdown. Nothing is shown

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#285]
Teacher--> Resources--> class 8--> select 05 "playing with numbers". It has topic and games. Click on view game dropdown. Nothing is shown

**Comment by mouparnadas** [comment]
The games section has content. 
![capture](https://cloud.githubusercontent.com/assets/17062939/12990251/6a5fd4e2-d12f-11e5-8327-fe172f14dfad.JPG)

**Comment by summar1** [comment]
![image](https://cloud.githubusercontent.com/assets/16289032/12993310/648ab7fc-d13f-11e5-8353-e21b83bc2deb.png)
 when user selects game from drop down nothing is shown

**Comment by mouparnadas** [comment]
Will be available in next deployment

**Comment by supriti-mukherjee** [comment]
Fixed
