### ISSUE TITLE
Teacher--> Resources--> class 8--> Select a resource which has games. InitiAlly the collapsible arrow is not correctly showing. User has to click on it and then it works correctly. same is for toolkit and investigation collapsible arrow

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#286]
Teacher--> Resources--> class 8--> Select a resource which has games. InitiAlly the collapsible arrow is not correctly showing. User has to click on it
and then it works correctly. same is for toolkit and investigation collapsible arrow

**Comment by OUPGandhinagar** [comment]
Duplicated... Bug UI defect #140, Please close this. will work on it & update it on #140

**Comment by mouparnadas** [comment]
Duplicate please close this
