### ISSUE TITLE
Log on into the application as OUPADMIN and click on create notification. select both school admin and principal in the recipient. (the school should have a principal) and create the notification. Now click on edit or copy.Principal field is shown but its chec kbox in unchecked

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#287]
Log on into the application as OUPADMIN and click on create notification. select both school admin and principal in the recipient. (the school should have a principal) and create the notification. Now click on edit or copy.Principal field is shown but its chec kbox in unchecked

**Comment by pankaj44** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Fixed
