### ISSUE TITLE
Schools with long name are not reflecting properly under the Advance search

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#29]
Log on into the application as OUP admin and click on Advance search. Select a school with long name from the dropdown. Schools with long name are not reflecting properly under the Advance search. The name is hidden behind the dropdown button
![schoolname](https://cloud.githubusercontent.com/assets/16289032/12113724/c78b97dc-b3ca-11e5-9ee8-06205e2b8923.jpg)

**Comment by supriti-mukherjee** [comment]
The widths of all the fields are aligned with each other. So nothing can be done for that.

**Comment by summar1** [comment]
School with longer names can show 10-15 characters and then 3... , something like that. this is not looking good

**Comment by supriti-mukherjee** [comment]
width of the dropdown cant be changed, then UI will be distorted.

**Comment by summar1** [comment]
Fixed
