### ISSUE TITLE
School update warning message

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#294]
Casing issue.(Words in a sentence should start with capital letter)

![defect2](https://cloud.githubusercontent.com/assets/11663550/13013391/4b21c2d8-d1d5-11e5-8c61-8594319354e5.PNG)

**Comment by mouparnadas** [comment]
Fixed. Will be available in next deployment.

**Comment by supriti-mukherjee** [comment]
Fixed
