### ISSUE TITLE
Log on into the application as teacher and go to create activity. Create an activity and try to search the activity created. two records are shown.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#295]
Log on into the application as teacher and go to create activity. Create an activity and try to search the activity created. two records are shown.
![3](https://cloud.githubusercontent.com/assets/16289032/13026084/4c425422-d241-11e5-9ca7-863aa2d05c28.jpg)

**Comment by supriti-mukherjee** [comment]
as per business requirement
