### ISSUE TITLE
 there should be a space between "at least"

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#297]
log on into the application as teacher and do an activity / task search. Click on the delete selected link without selecting any checkbox. The pop message
there it "please select atleast one activity". there should be a space between "at least"
![4](https://cloud.githubusercontent.com/assets/16289032/13026161/5809691e-d244-11e5-9fa2-e06f93eae340.jpg)

**Comment by mouparnadas** [comment]
Fixed. This will be available in next deployement

**Comment by supriti-mukherjee** [comment]
Fixed
