### ISSUE TITLE
log on into the application as teacher and create a task for a class section. Now search the task and click on the edit icon. User is redirected to the edit page. Click on the reset button. The page is reset but at the top its heading is still "Edit Task". The heading should also be changed to "Assign Task" as once the reset button is clicked the page is behaving as new task creation page.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#298]
log on into the application as teacher and create a task for a class section. Now search the task and click on the edit icon. User is redirected to the
edit page. Click on the reset button. The page is reset but at the top its heading is still "Edit Task". The heading should also be changed to "Assign Task"
as once the reset button is clicked the page is behaving as new task creation page.

![5](https://cloud.githubusercontent.com/assets/16289032/13026206/8ff9aebe-d245-11e5-86f5-2b0d24ae3214.jpg)

**Comment by manasghosh81** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Fixed
