### ISSUE TITLE
Teacher login--> When user clicks on the edit icon of the task then the heading of the redirected page is "Edit Task" and when the user clicks the edit icon of the activity, the redirected screen heading says "Update Activity". It should be made uniform for both eith update or edit.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#299]
Teacher login--> When user clicks on the edit icon of the task then the heading of the redirected page is "Edit Task" and when the user clicks the edit
icon of the activity, the redirected screen heading says "Update Activity". It should be made uniform for both eith update or edit.

**Comment by manasghosh81** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
The issue arising again 
![image](https://cloud.githubusercontent.com/assets/16289032/13072493/b77a42f6-d4bf-11e5-9870-e6dbd1e36e12.png)

**Comment by summar1** [comment]
Fixed. both screen heading is showing as edit task/activity now
