### ISSUE TITLE
Field length to be specified for the text fields

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#3]
User is able to input infinite characters in the "School Name", Address, First Name , Last name etc fields, however they are not allowed to save the details. 
Can a check for the field lengths be provided

**Comment by supriti-mukherjee** [comment]
Input length restriction was there for School Name and Address.
Input length restriction for First name,middle name and last name has been implemented and will be visible in the next deployment.
As per our data model the input lengths are-
School name-100 characters
Board Affiliation and Website-50 characters
Address line1 and Address line2-200 characters
Country,City,State-100 characters
Pincode-10 characters
First Name,Last Name-100 characters
Middle Name-50 characters

**Comment by summar1** [comment]
working
