### ISSUE TITLE
Deactivate selected link under advance search/ search is not working properly

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#30]
Without selecting any user click on the deactivate selected link. Its showing the "Information message" to select the user three time. Select some users through the checkbox and click on deactivate selected, still the information message to select a user is thrown three times and
  after that a confirmation message stating the selected users has been deactivated is shown

**Comment by supriti-mukherjee** [comment]
Fixed. Please check it once.

**Comment by summar1** [comment]
Fixed now
