### ISSUE TITLE
Teacher--. search task--> The assign button can be changed to "update"

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#301]
Teacher--. search task--> The assign button can be changed to "update"

![7](https://cloud.githubusercontent.com/assets/16289032/13026322/b56d994a-d249-11e5-8ab9-28c9955b8658.jpg)

**Comment by manasghosh81** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Fixed
