### ISSUE TITLE
URL encryption

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#302]
change userId from URL by logging as a student -> Student will be able to view OUPADMIN's profile.
Similarly, change schoolId from URL by logging as a schooladmin -> School admin will be able to view other school's profile

**Comment by manasghosh81** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
not implemented for student my task and my activity

**Comment by manasghosh81** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
URL encryption for student individual report by teacher is not implemented

**Comment by manasghosh81** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Fixed
