### ISSUE TITLE
OUPADMIN Advance Search

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#303]
Login as OUPADMIN -> Advance Search -> Select Inactive records from dropdown and Search -> All the inactive records are displayed -> Check on the selectall checkbox -> Click on the 'deactivate selected' -> warning message for deactivation and confirmation message of users deactivated is coming up -> records in the page are going -> again perform a search of inactive records -> records which appeared to be deleted are displayed.

**Comment by manasghosh81** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Fixed
