### ISSUE TITLE
Search School by OUPADMIN

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#307]
Login as OUPADMIN ->  Search School -> Select Inactive schools from dropdown and Search -> All the inactive records are displayed -> Check on the selectall checkbox -> Click on the 'deactivate selected' -> warning message for deactivation and confirmation message of schools deactivated is coming up -> records in the page are going -> again perform a search of inactive schools -> records which appeared to be deleted are displayed

**Comment by manasghosh81** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Fixed
