### ISSUE TITLE
UI Defect

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#309]
Investigation text and arrow is overlapping.

![defect4](https://cloud.githubusercontent.com/assets/11663550/13032419/cba4b7ec-d317-11e5-836b-65f7b30dbe2e.PNG)

**Comment by OUPGandhinagar** [comment]
Already Fixed & verified with Supriti

**Comment by supriti-mukherjee** [comment]
Fixed
