### ISSUE TITLE
OUPADMIN - advance search and utilities

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#315]
select school from dropdown -> select class and section from dropdown -> change the selected school from dropdown again -> class dropdown is resetting but not section dropdown

**Comment by summar1** [comment]
Fixed for utilities. Still existing in Advance search

**Comment by mouparnadas** [comment]
Fixed. This will be available in next deployment.

**Comment by supriti-mukherjee** [comment]
Fixed
