### ISSUE TITLE
Text Change in Assign Task

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#318]
"Assign Tasks" should be "Assign Task" 

![image34](https://cloud.githubusercontent.com/assets/11663550/13041943/d268a06e-d3e1-11e5-9cce-7dedb587c1fe.PNG)

**Comment by mouparnadas** [comment]
Will be available in next deployment

**Comment by supriti-mukherjee** [comment]
Fixed
