### ISSUE TITLE
School admin my profile contact no issue

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#330]
Log on into the application as OUP Admin and register a new school. Here in the school admin section the contact field is a mandatory field. Now log on into the application as school admin and check my profile. Here the contact no is a non mandatory field. so keeping it blank user is able to update the profile. Now log as OUP Admin and go to school search and try to edit the school. The school admin details section, contact no which is a mandatory field is shown as blank. 
Need to make contact no mandatory in User profile too

**Comment by manasghosh81** [comment]
Fixed

**Comment by summar1** [comment]
Fixed now
