### ISSUE TITLE
School Amin--> Classes--> Select a class and click on Go--> Class details is shown. Click on the "delete selected" link without making any selection The pop up message says " Please select at least one teacher to delete"

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#332]
School Amin--> Classes--> Select a class and click on Go--> Class details is shown. Click on the "delete selected" link without making any selection
The pop up message says " Please select at least one teacher to delete"
![image](https://cloud.githubusercontent.com/assets/16289032/13075891/882173a2-d4d4-11e5-8f8f-3a9b0da1056a.png)

**Comment by pankaj44** [comment]
Not a defect

**Comment by summar1** [comment]
Fixed now. Its showing chose one SECTION to delete now.

![image](https://cloud.githubusercontent.com/assets/16289032/13202520/aed48546-d8c3-11e5-83d6-70001e4d7825.png)
