### ISSUE TITLE
Teacher --> create task--> scroll bar needs to be provided for huge data for chapter and topics

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#333]
Teacher --> create task--> scroll bar needs to be provided for huge data for chapter and topics

**Comment by manasghosh81** [comment]
Fixed

**Comment by OUPGandhinagar** [comment]
![image](https://cloud.githubusercontent.com/assets/16717199/13078249/cee40804-d4e3-11e5-9e4c-742d0a2d5b6f.png)

Dynamic Scroll bar is already there.. This list will not come out of screen. Once its reached height limit of browser window scroll bar automatically added.

**Comment by summar1** [comment]
ok
