### ISSUE TITLE
Print hyperlink

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#344]
Provide hyperlink 
![image41](https://cloud.githubusercontent.com/assets/11663550/13104321/74a1e1e6-d582-11e5-99b7-aefcc3e4ac12.PNG)

**Comment by mouparnadas** [comment]
Please retest

**Comment by supriti-mukherjee** [comment]
Not fixed

**Comment by supriti-mukherjee** [comment]
Fixed
