### ISSUE TITLE
Drag image

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#348]
drag over the image..data is shown

![image44](https://cloud.githubusercontent.com/assets/11663550/13105594/f9f4381a-d589-11e5-8d36-c91b70b52478.PNG)

**Comment by OUPGandhinagar** [comment]
This is not a defect, Its by default feature of Chrome. you will not find the same on another browser. I have disable with CSS for chrome. you will get it on next check in.

**Comment by OUPGandhinagar** [comment]
Checked in !!

**Comment by supriti-mukherjee** [comment]
Fixed
