### ISSUE TITLE
Class section details of the teacher is not getting reflected if the OUP Admin clicks on the (…) after some time of doing other activities in that page

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#35]
Class and section of the teacher is notreflected after sometime. User has to refresh the page to view the details
![classsection](https://cloud.githubusercontent.com/assets/16289032/12142512/9e84b6c8-b49e-11e5-956d-01a8387bd2bb.jpg)
![classsection1](https://cloud.githubusercontent.com/assets/16289032/12142515/a669a542-b49e-11e5-8f0e-0d995865e097.jpg)

**Comment by supriti-mukherjee** [comment]
It is fixed now.

**Comment by summar1** [comment]
Fixed
