### ISSUE TITLE
Student Performance Report

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#353]
Tooltip should not come for text.

![image46](https://cloud.githubusercontent.com/assets/11663550/13113152/deaefbce-d5b3-11e5-81df-eb8598f23b9a.PNG)

**Comment by OUPGandhinagar** [comment]
We have placed tooltip because if there is Big name which out limit.. so tooltip will help in that case..

![image](https://cloud.githubusercontent.com/assets/16717199/13135628/82645456-d638-11e5-84be-cee6737703dd.png)

**Comment by supriti-mukherjee** [comment]
Fixed
