### ISSUE TITLE
Chapter name in create task and search task is coming different

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#355]
Log on into the application as teacher and assign a task for chapter ( time or substraction). Now search the task by class filter. In the search grid the chapter column is showing data as ( Ration & Proportion and Playing with numbers) respectively
![image](https://cloud.githubusercontent.com/assets/16289032/13136716/f3c343c4-d641-11e5-9e36-c495d2a465be.png)
![image](https://cloud.githubusercontent.com/assets/16289032/13136729/00501842-d642-11e5-9c24-e201f6c919ef.png)

**Comment by manasghosh81** [comment]
Not a defect.
Chapter drop down will only show the Chapter Code:Chapter Name.

**Comment by summar1** [comment]
Uers has selected "substraction" as chapter name but in the search grid chapter name is coming different
![image](https://cloud.githubusercontent.com/assets/16289032/13202662/2cbb7330-d8c8-11e5-9a56-fe0094b27032.png)

**Comment by mouparnadas** [comment]
Fixed

**Comment by summar1** [comment]
Fixed now
