### ISSUE TITLE
task status report

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#359]
teacher -> reports -> task status reports -> completion status(4 of 5).
now login as a school admin -> transfer one of the 4 students (who have attempted the task) to some different section.
again teacher -> reports -> task status reports -> completion status(4 of 5) -> click on the pop up -> student who was transferred is not coming in pop up.

**Comment by pankaj44** [comment]
Next QA build

**Comment by supriti-mukherjee** [comment]
Fixed
