### ISSUE TITLE
If user deactivate all the students and again try to Upload the same sheet then its throwing error

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#36]
Log on into the application as OUP admin and create a school and upload student and teacher details. Now go to the search/Advance search and select all the students and click on deactivate selected. All the students are deactivated now. Again try to upload the same sheet without making any changes to the same school. Its showing
  error as "Student already exist with same name and class section.

**Comment by supriti-mukherjee** [comment]
Please check it once.

**Comment by summar1** [comment]
Fixed
