### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#366]
Login as OUPADMIN -> Deactivate students of a particular section who have attempted tests and reports are present -> Login as a teacher -> Search reports for that particular section -> "No Data Found" is displayed. Though the students are deactivated but as they have attempted the tasks, records should be visible by teacher.

**Comment by pankaj44** [comment]
Next QA deplyoment

**Comment by supriti-mukherjee** [comment]
Deactivated student reports are available for Class Performance and Task Status but not for Student Performance.

**Comment by pankaj44** [comment]
Plz check once again

**Comment by supriti-mukherjee** [comment]
Deactivated student reports are available for Class Performance and Task Status but not for Student Performance.

**Comment by supriti-mukherjee** [comment]
Fixed
