### ISSUE TITLE
Duplicate user name is getting created

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#37]
Duplicate user name is getting created. Try to upload a sheet containing same student name for same class/ section and for different class section.
In this case duplicate user name is getting created. 
![duplicate](https://cloud.githubusercontent.com/assets/16289032/12142534/dc858d4e-b49e-11e5-9794-b693faaec6b8.jpg)

**Comment by supriti-mukherjee** [comment]
It is fixed. Please check it once.

**Comment by summar1** [comment]
Fixed
