### ISSUE TITLE
UI of the message pop is distorted

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#370]
OUP ADMIn--> Edit school--> try to edit all the dated --> The pop up message, cancel button is shifted down. It should be in line with other button

![image](https://cloud.githubusercontent.com/assets/16289032/13170553/e18bc3f8-d712-11e5-88b3-9a1ce85bd9e2.png)

**Comment by OUPGandhinagar** [comment]
Done in Local & checked in SVN.

**Comment by summar1** [comment]
Fixed now.

![image](https://cloud.githubusercontent.com/assets/16289032/13202536/71979b22-d8c4-11e5-94d8-1f229cc76998.png)
