### ISSUE TITLE
Teacher login --> search task --> Topic is remaining disabled and blank so user is not able to update the task

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#371]
Teacher login --> search task --> Topic is remaining disabled and blank so user is not able to update the task
![image](https://cloud.githubusercontent.com/assets/16289032/13172277/56263482-d71d-11e5-8b0c-60d0c357f8d6.png)

**Comment by manasghosh81** [comment]
Not replicable

**Comment by summar1** [comment]
![image](https://cloud.githubusercontent.com/assets/16289032/13202549/cbf042f4-d8c4-11e5-91d9-6caed2ba9b52.png)

still exists in QA

**Comment by summar1** [comment]
ok now
