### ISSUE TITLE
UI --> Student dashboard--> Task

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#372]
student dashboard--> The topic name should not touch the boundary of the tiles

![image](https://cloud.githubusercontent.com/assets/16289032/13173315/dea60436-d722-11e5-8d5c-9f9f07be608e.png)

**Comment by OUPGandhinagar** [comment]
Done in Local & checked in SVN.

**Comment by summar1** [comment]
Fixed now
