### ISSUE TITLE
school admin report

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#376]
text should be 'for' instead of 'between'
![image50](https://cloud.githubusercontent.com/assets/11663550/13175734/72e48b54-d732-11e5-8037-ca7861e56c73.PNG)

**Comment by manasghosh81** [comment]
Invalid

**Comment by supriti-mukherjee** [comment]
remove multiple 'and' from 1st graph

**Comment by manasghosh81** [comment]
fixed

**Comment by supriti-mukherjee** [comment]
Fixed
