### ISSUE TITLE
Section Wise Comparison Report

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#378]
school admin -> Reports -> select class,section and go -> select one chapter for which task is attempted and one chapter for which task is not attempted -> go -> in the chapter names for second graph, name of the chapter which has not been attempted is not coming

**Comment by manasghosh81** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Not Fixed

**Comment by supriti-mukherjee** [comment]
fixed
