### ISSUE TITLE
Teacher not assigned to that class and section is getting reflected

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#38]
Log on into the application as OUP Admin and go to advance search. Advance search - For Class section Combination, Teacher who has not been assigned to any class or section is also getting reflected
![sccombo](https://cloud.githubusercontent.com/assets/16289032/12142549/fd81bffe-b49e-11e5-9db3-5bd59473f899.jpg)
![sccombo1](https://cloud.githubusercontent.com/assets/16289032/12142553/047f3084-b49f-11e5-8831-d6f7fda3730d.jpg)

**Comment by supriti-mukherjee** [comment]
It is fixed. please check it once.

**Comment by summar1** [comment]
Fixed
