### ISSUE TITLE
--> School Admin--> Classes--> View class details--> select a class from dropdown and click on "Go". The "Loading" button remains in the screen and does not goes away.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#383]
--> School Admin--> Classes--> View class details--> select a class from dropdown and click on "Go". The "Loading" button remains in the screen and
does not goes away.
![image](https://cloud.githubusercontent.com/assets/16289032/13201176/a0f71024-d88c-11e5-9ecc-51c19a3750d9.png)

**Comment by mouparnadas** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
