### ISSUE TITLE
School Admin--> Reports--> Score comparision between two sections--> the score for scetion A is available at top of the bar, but the score of section B is not visible at the top of the bar.Also if the report is further drill down to chapter wise score then the chapter name in the X axis is not aligned  properly

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#385]
School Admin--> Reports--> Score comparison between two sections--> the score for sction A is available at top of the bar, but the score of section
B is not visible at the top of the bar.Also if the report is further drill down to chapter wise score then the chapter name in the X axis is not aligned
 properly
![image](https://cloud.githubusercontent.com/assets/16289032/13201276/acc20a14-d88f-11e5-8b15-8ec8f5af8d27.png)

**Comment by manasghosh81** [comment]
Not a defect

**Comment by summar1** [comment]
When the bar graph touches the maximum limit in the graph then the values are not reflecting at the top. Also in the chapterwise graph the value of X axis is not aligned properly

**Comment by manasghosh81** [comment]
Not a defect.. Please talk to subha...

**Comment by summar1** [comment]
ok
