### ISSUE TITLE
OUPADMIN Advance Search

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#388]
OUPADMIN -> Advance search -> Search for a teacher who have multiple classes -> Following pop up comes up
![image12](https://cloud.githubusercontent.com/assets/11663550/13202862/b43c03dc-d8ce-11e5-8b09-eca084f2c226.PNG)
1) Text of "Showing entries data..." is wrong.
2) Where is search button for search textbox? 
3) Pop up UI is distorted
4) Change show count -> No Data Found is displayed

**Comment by manasghosh81** [comment]
not replicable

**Comment by supriti-mukherjee** [comment]
Fixed
