### ISSUE TITLE
Register to and Register from date filled with other dates then actual registration date is generating data

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#39]
Log on into the application as OUP Admin and go to advance search. Fill the registration to or registration from field with any date (not the actual date provided) ,after doing some other search, and click on search. 
Data is getting reflected
![regfrom](https://cloud.githubusercontent.com/assets/16289032/12142566/1bde9e7c-b49f-11e5-888f-c8072c4b9eca.jpg)
![regto](https://cloud.githubusercontent.com/assets/16289032/12142568/21951706-b49f-11e5-8321-cab747822578.jpg)

**Comment by supriti-mukherjee** [comment]
It is fixed now.

**Comment by summar1** [comment]
Not Fixed

**Comment by summar1** [comment]
Fixed
