### ISSUE TITLE
Remedial Task

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#395]
1) Remedial task icon is not aligned properly.
2) Remedial task count should be displayed.
3) For the completed task if remedial created, it should be displayed in the tile-"Remedial Task Created"

**Comment by OUPGandhinagar** [comment]
1) Remedial task icon is not aligned properly.- DONE in local..& checked in SVN

**Comment by supriti-mukherjee** [comment]
Fixed
