### ISSUE TITLE
OUPADMIN Utilities

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#396]
OUPADMIN -> Utilities -> Give name of school only in search criteria -> In teacher search result grid, the teacher which have multiple sections is displaying only the first section(rest of the sections are not displayed)

**Comment by pankaj44** [comment]
Need to discussed with Subho da

**Comment by pankaj44** [comment]
Next QA build

**Comment by supriti-mukherjee** [comment]
Fixed
