### ISSUE TITLE
Teacher --> Assign Task-->Section name not coming properly

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#398]
Teacher --> Assign Task-->Section name not coming properly

It should be A, B, C, Red instead of A, C, B , Red

![image](https://cloud.githubusercontent.com/assets/16289032/13217864/a470349c-d98b-11e5-8094-5370dcc39217.png)

**Comment by mouparnadas** [comment]
Fixed and the changes will be available in next deployment.

**Comment by supriti-mukherjee** [comment]
Not fixed

**Comment by manasghosh81** [comment]
fixed

**Comment by summar1** [comment]
Fixed
