### ISSUE TITLE
Subscription start date - end date is greater then academic start date - academic end date still the school is getting created

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#4]
Subscription start date - end date is greater then academic start date - academic end date still the school is created successfully.
Refer to the screenshot attached  date.jpg
![dates](https://cloud.githubusercontent.com/assets/16289032/11924841/84270738-a7db-11e5-9001-820685bc929c.jpg)

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
