### ISSUE TITLE
School Admin--> edit  deactivate and restore teacher

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#404]
School Admin--> go to create new teacher and create a teacher. Click on basic/advance search and search the created teacher. and click on the delete icon in the action column. The teacher is deactivated. As per FSD deleted records will be activated by OUPI Admin only, but if school admin deletes a teacher record then restore and edit icons are available in the action column. If user clicks on the edit icon then he is redirected to the log in page showing access denied. Also school admin is able to activate a deactivated teacher

**Comment by manasghosh81** [comment]
fixed

**Comment by summar1** [comment]
User is redirected to user's profile page now
