### ISSUE TITLE
Search Activity

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#405]
teacher -> classes -> assign activity to students of multiple sections -> search activity -> click on the section (...) -> only the students of the first section are displayed in the pop up

This needs to be fixed - it is not a data issue. Same issue exists for task

**Comment by manasghosh81** [comment]
Please retest with new data.

**Comment by summar1** [comment]
Fixed now 

![image](https://cloud.githubusercontent.com/assets/16289032/13295826/9f30f48c-db50-11e5-8277-6d463b9218b6.png)

![image](https://cloud.githubusercontent.com/assets/16289032/13295845/ba36e9da-db50-11e5-820d-cab67d156b8d.png)
