### ISSUE TITLE
Resources by Teacher

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#406]
Teacher -> resources -> close the topics grid by clicking on the arrow -> now change the class from dropdown -> the grid is getting distorted

![image54](https://cloud.githubusercontent.com/assets/11663550/13252741/61b3a61a-da5e-11e5-9b1f-8fc8bf9ef762.PNG)

**Comment by OUPGandhinagar** [comment]
Done & checked in...

**Comment by supriti-mukherjee** [comment]
Fixed
