### ISSUE TITLE
As per the FSD, the Action column should also contain an icon to view and transfer student's details,but it is not available.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#41]
Log on into the application as School Admin and click on Class. Select a class and click on “go”. As per the FSD, the Action column should also contain an icon to view and transfer student's details,but it is not available.
![view](https://cloud.githubusercontent.com/assets/16289032/12142589/48f48296-b49f-11e5-8222-14c2aa99b768.jpg)

**Comment by supriti-mukherjee** [comment]
View students icon will be available if that class-section is having students. It is working fine for the class-section which contains students.

**Comment by summar1** [comment]
Even if a class section was having students then also view button was not available earlier. Now its working as desired
