### ISSUE TITLE
Teacher--> when a user updates a task then the message heading is "confirmation" and its body says "task has been updated successfully!". But if the user updates an activity then the message heading is "Information" and the body says "Activity updated successfully". Both of it should be uniform

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#411]
Teacher--> when a user updates a task then the message heading is "confirmation" and its body says "task has been updated successfully!". But if the
user updates an activity then the message heading is "Information" and the body says "Activity updated successfully". Both of it should be uniform

**Comment by manasghosh81** [comment]
fixed

**Comment by summar1** [comment]
Fixed and working as desire
