### ISSUE TITLE
Edit profile

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#419]
Position of message not right when editing profile from Search-> Edit Profile

**Comment by mouparnadas** [comment]
Fixed available in next deployment

**Comment by supriti-mukherjee** [comment]
School name not present in view student profile by OUPADMIN.

**Comment by mouparnadas** [comment]
fixed

**Comment by summar1** [comment]
Fixed now 

![Uploading image.png…]()
