### ISSUE TITLE
Reset button not working

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#42]
Log on into the application as School Admin and click on Class. Select the class and section from drop down and click on "Go" the details are getting reflected. Now click on the reset button.  The details are removed but the selection made for class and section fields remain. And once you click on the reset button, then if you click on the "Go"
button for the same class it will not work. You have to make a change in the class field

**Comment by supriti-mukherjee** [comment]
It is fixed.

**Comment by summar1** [comment]
ok now
