### ISSUE TITLE
Bulk upload - see screenshot 

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#422]
![image58](https://cloud.githubusercontent.com/assets/11663550/13278329/be101dca-daf5-11e5-8ae2-e5ef6f5180d9.PNG)

**Comment by manasghosh81** [comment]
Fixed

**Comment by summar1** [comment]
Not working

**Comment by summar1** [comment]
Fixed now 

![image](https://cloud.githubusercontent.com/assets/16289032/13296591/4b0f9454-db54-11e5-9d69-1c7a3dadf5fe.png)
