### ISSUE TITLE
UI of the replace teacher window is not good.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#43]
UI of the replace teacher window is not good."Cancel button is reflecting twice. the "X" button to close the window is not properly aligned and the calendar icon is overlapping
![uireplace teacher](https://cloud.githubusercontent.com/assets/16289032/12142605/7a92c308-b49f-11e5-95c7-ae732daad349.jpg)

**Comment by supriti-mukherjee** [comment]
It is fixed.

**Comment by summar1** [comment]
ok now
