### ISSUE TITLE
School Admin report 

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#430]
Remove the word "section" from the first graph (below the bars), same for the legends of the 2nd graph

**Comment by manasghosh81** [comment]
Fixed

**Comment by summar1** [comment]
It should be section A not A

![image](https://cloud.githubusercontent.com/assets/16289032/13284462/6ed879bc-db1a-11e5-9821-a646374d0bfd.png)

**Comment by manasghosh81** [comment]
Not a defect. Section should be what ever there is in the section dropdown.

**Comment by supriti-mukherjee** [comment]
closed
