### ISSUE TITLE
Student Activity

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#435]
1. For activity, the system message has a line "Attempt the task before it expires" . change task to activity 
   1.  In View Activity page - the attachment should have "hand" icon for download
   2.  In View Activity page - if URL it should be hyperlinked 
   3.  For activity assignment notification, the text within message is not coming right (Teacher is coming multiple times)

**Comment by pankaj44** [comment]
Fixed Available in next QA

**Comment by supriti-mukherjee** [comment]
Fixed
