### ISSUE TITLE
School Admin Classes

### ISSUE THREAD

**Issue by supriti-mukherjee** [manasghosh81/MyMathsTesting#437]
School admin -> classes -> view class details -> select class from dropdown and search -> close grid by clicking on the arrow -> without changing anything click on go again -> UI is distorted

![image60](https://cloud.githubusercontent.com/assets/11663550/13284831/e40c736c-db1c-11e5-85d2-f71601055764.PNG)

**Comment by manasghosh81** [comment]
Fixed

**Comment by supriti-mukherjee** [comment]
Fixed
