### ISSUE TITLE
When user tries to edit a section then after successful edit the edited name doesn't reflect immediately User has to refresh the screen to view the updated data.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#44]
Log on into the application as School Admin and click on Class. Select the class and section from drop down and click on "Go". From the action column click on the edit icon. When user tries to edit a section then after successful edit the edited name doesn't reflect immediately User has to refresh the screen to view the
updated data.

**Comment by supriti-mukherjee** [comment]
Its working properly. After editing the section ,again select the section from from dropdown, click on Go and the updated section name can be viewed. This is the proper flow.

**Comment by summar1** [comment]
ok
