### ISSUE TITLE
School Admin--> Classes--> select a class and click on go. View students from a section. From "student in class" grid try to do a student transfer. In the transfer section pop up, provide an existing section name in the "new section name" and try to update. The error message says "Section Name is already exist" It should be "Section name already exists !"

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#441]
School Admin--> Classes--> select a class and click on go. View students from a section. From "student in class" grid try to do a student transfer. In the
transfer section pop up, provide an existing section name in the "new section name" and try to update. The error message says "Section Name is already exist"
It should be "Section name already exists !"

**Comment by mouparnadas** [comment]
Fixed. Available in next deployment.

**Comment by summar1** [comment]
Fixed now
