### ISSUE TITLE
UAT- A teacher is assigned to two section of a class lets say section A and c. He creates a task for both of these section. In search task he can view two rows one says the value "all" under section and one "C". It should be "A" and "C". Same for activity

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#443]
UAt- A teacher is assigned to two section of a class lets say section A and c. He creates a task for both of these section. In search task he can view two rows one says the value "all" under section and one "C". It should be "A" and "C". Same for activity

**Comment by manasghosh81** [comment]
Not a defect. Please retest with new data.

**Comment by summar1** [comment]
Fixed now
