### ISSUE TITLE
select the section which contain student and the section which does not contain any student. Click on "deactivate selected". All the sections are getting  deleted. This should not happen. A warning message should be thrown stating one of the section contains students.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#45]
select the section which contain student and the section which does not contain any student. Click on "deactivate selected". All the sections are getting 
deleted. This should not happen. A warning message should be thrown stating one of the section contains students.

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
