### ISSUE TITLE
Random message displayed behind the confirmation message

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#48]
Log on into the application as OUP admin and go to school register page. Fill all the required data successfully and click on register. Random message displayed behind the confirmation message
![random message](https://cloud.githubusercontent.com/assets/16289032/12142702/43d82b04-b4a0-11e5-9fce-536c3dd3e41d.jpg)

**Comment by supriti-mukherjee** [comment]
It is fixed and can be seen in next deployment.

**Comment by summar1** [comment]
Fixed
