### ISSUE TITLE
The Class page is not aligned properly as per the UI

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#49]
The Class page is not aligned properly as per the UI
![ui](https://cloud.githubusercontent.com/assets/16289032/12171340/243c13f8-b56f-11e5-9fdf-f8ed422913f7.jpg)

**Comment by supriti-mukherjee** [comment]
It is fixed and can be seen after next deployment.

**Comment by summar1** [comment]
OK
