### ISSUE TITLE
Close buttons “ok” and “X” on the pop up message is not behaving properly

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#5]
Log on into the application as OUP Admin and click on the register school link. Fill all the required mandatory details properly and click on 
  Register button. A success message is displayed which had a "OK" button and a "X" button at the right side top cornor, both for closing the message.
  When user clicks on the "OK" button then, a new school registration page is available  but when the user clicks on the "X" button then the school details 
  remain on the page and in the editable form, however user is not able to save the details. In both the cases the new school registration page should open.

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Working now
