### ISSUE TITLE
Edit button issue for past date notifications

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#50]
Log on into the application as OUP admin and click on create notification. Create a notification for present system date and click on send. The notification details are generated in the grid below however the Action column contains only copy icon. As per the FSD, edit icon should also be available on click of which the notification details should be shown with all the fields is disable form. Atleast n icon to view details can be provided

**Comment by supriti-mukherjee** [comment]
It is fixed and will be available in next deployment.

**Comment by summar1** [comment]
Send on date is not disable

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
