### ISSUE TITLE
Error message is thrown

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#51]
Log on into the application as OUP admin and click on create notification. When user has not selected any school  then two check option for recipient
 is available- School Admin and Principal. Select both the check box and then select a school. The principal option is removed. Now fill all the details
and click on send/schedule as per the date selection. An error message is thrown stating "No principal associated with this school"
![princi](https://cloud.githubusercontent.com/assets/16289032/12171659/be2ae30c-b571-11e5-81e7-7c4605f1c12f.jpg)

**Comment by supriti-mukherjee** [comment]
It is resolved and can be seen on next deployment.

**Comment by summar1** [comment]
Need to discuss this

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
