### ISSUE TITLE
As per the FSD, the confirmation message displayed after a successful registration of school should contain school name along with the city name but in the application only school name is shown.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#52]
As per the FSD, the confirmation message displayed after a successful registration of school should contain school name along with the city name
but in the application only school name is shown.
![city](https://cloud.githubusercontent.com/assets/16289032/12197220/32dbb456-b62b-11e5-8d8c-dd841bf6ed2d.jpg)
![city1](https://cloud.githubusercontent.com/assets/16289032/12197227/3d000f0e-b62b-11e5-836f-33bcb31a2076.jpg)

**Comment by supriti-mukherjee** [comment]
![registerschool](https://cloud.githubusercontent.com/assets/11663550/12198769/f32dbf94-b638-11e5-9656-2f7ba1af8769.PNG)
According to the latest FSD, City name is not displayed while registering new school. Please go through it once.

**Comment by summar1** [comment]
Fixed
