### ISSUE TITLE
Error message not prompt

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#53]
Keeping the website and email field which are non mandatory field of address detail section of Register school link, blank click on the register button. As per the FSD error message should be prompt but in the application only the textboxes are highlighted in red

**Comment by supriti-mukherjee** [comment]
Highlighting the textboxes red is a type of error message. non-mandatory fields will not be marked red(website and email)

**Comment by summar1** [comment]
ok
