### ISSUE TITLE
After selecting 6 rows can the add button be removed from last row, as there is no delete button for the 1st row

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#55]
After selecting 6 rows can the add button be removed from last row, as there is no delete button for the 1st row
![add](https://cloud.githubusercontent.com/assets/16289032/12197257/8a031f9e-b62b-11e5-93aa-df1162e5ec6e.jpg)

**Comment by supriti-mukherjee** [comment]
It is implemented and will be available after next deployment.

**Comment by summar1** [comment]
![1](https://cloud.githubusercontent.com/assets/16289032/12232204/07fc8698-b883-11e5-8149-39187d431d6b.jpg)

still the same

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
