### ISSUE TITLE
Contact field is taking alphabets and saving data successfully

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#57]
Try to navigate the Contact Us screen from Home Page. Contact field is taking alphabets and saving data successfully

**Comment by supriti-mukherjee** [comment]
Implemented and can be seen after next deployment.

**Comment by summar1** [comment]
Not working properly  look into issue #73

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
