### ISSUE TITLE
If the school admin wants to share same notification to different sections of the same class he has to copy it and send. Can we also provide checbox  for the LOV values of Dropdown field section so that it will be easy.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#58]
Log on into the application as school admin and go to create notification. If the school admin wants to share same notification to different sections of the same class he has to copy it and send. Can we also provide check box
 for the LOV values of Dropdown field section so that it will be easy.

**Comment by supriti-mukherjee** [comment]
It is working as per requirement.

**Comment by summar1** [comment]
ok
