### ISSUE TITLE
Deleted section doesn't get removed. User has to revisit the page to view updated data

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#59]
Log on into the application as school admin and click the classes link. Select a class and click on go. From the search grid try to delete a section. When user click on the delete icon against a section then even if the success message is shown that the section has been deleted, still the data doesn't go away
User has to again click on go or revisit the page to view the updated data

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
