### ISSUE TITLE
Tool tip showing incorrect button name

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#6]
Log on into the application as a OUP Admin. Create a school and go to the school search page. Search the created school and deactivate it. Now when user takes  the cursor to the activate button, the tool tip says "deactivate school". It should be "Activate school". 
Refer to the screenshot attached - activateschool.jpg
![activateschool](https://cloud.githubusercontent.com/assets/16289032/11924883/eddefa28-a7db-11e5-9045-7b0a55a2a373.jpg)

**Comment by supriti-mukherjee** [comment]
Implemented.

**Comment by summar1** [comment]
workinh now
