### ISSUE TITLE
Blank error message is displayed

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#60]
Log on into the application as OUP/School Admin and try to create a notification.
When the subject and message field of notification crosses its text limit and user click on the send/schedule button then a error message is displayed
which is blank.
![error message](https://cloud.githubusercontent.com/assets/16289032/12231897/c928528c-b880-11e5-9930-651a64e6ed29.jpg)

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
