### ISSUE TITLE
The pop up message opened contains the earlier filled Section name in the "Add section and select" link

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#61]
Log on into the application as school admin and go to classes. . Try to do a search for a class. From the list displayed click on the view icon for a 
particular class to view the student details. Select a student and click on the transfer button. A pop up message is displayed. Fill the new section
name ad click on add section and select. Then again come back to another student and try to transfer him/her. The pop up message opened contains the earlier
filled Section name in the "Add section and select" link

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
