### ISSUE TITLE
Log on into the application as school admin and go to classes. . Try to do a search for a class. From the list displayed click on the delete icon. The message says a "..... deleted the selected....." It should be ..."...delete....". (delete not deleted).

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#62]
Log on into the application as school admin and go to classes. . Try to do a search for a class. From the list displayed click on the delete icon. The
message says a "..... deleted the selected....." It should be ..."...delete....". (delete not deleted).
![delete](https://cloud.githubusercontent.com/assets/16289032/12231938/1dd6dbe6-b881-11e5-8f3c-2f9eba8cad80.jpg)

**Comment by supriti-mukherjee** [comment]
it is fixed now. It can be seen after next deployment.

**Comment by summar1** [comment]
Fixed
