### ISSUE TITLE
 Log on into the application as School Admin and click on class. Search a class section. From the search list grid click on the replace teacher and try to do a blank search. User is getting list of data. As per the rule Blank search should not work.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#63]
Log on into the application as School Admin and click on class. Search a class section. From the search list grid click on the replace teacher and try to
do a blank search. User is getting list of data. As per the rule Blank search should not work.
![replace teacher](https://cloud.githubusercontent.com/assets/16289032/12231967/4de1c8c8-b881-11e5-94f9-aa8a5f7effe0.jpg)

**Comment by supriti-mukherjee** [comment]
fixed

**Comment by summar1** [comment]
Fixed
