### ISSUE TITLE
Log on into the application as School Admin and click on class.For the view class details tab without selecting the class click on the 'add section " button the class field is highlighted in red. Now select a class and then click on reset. Although the value is reset still the class fields is glowing in red.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#65]
Log on into the application as School Admin and click on class.For the view class details tab without selecting the class click on the 'add section " button
the class field is highlighted in red. Now select a class and then click on reset. Although the value is reset still the class fields is glowing in red.

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
