### ISSUE TITLE
The section dropdown is showing the students current section also.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#66]
Log on into the application as school admin and go to classes. . Try to do a search for a class. From the list displayed click on the view icon for a 
particular class to view the student details. Select a student and click on the transfer button. A pop up message is displayed. The section dropdown is showing the
students current section also.

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
