### ISSUE TITLE
Teacher and student search grid should be collapsible.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#67]
Log on into the application as School / OUP Admin and click on Utilities--> the teacher and student search grid should be collapsible.
![utilities](https://cloud.githubusercontent.com/assets/16289032/12232031/d406f806-b881-11e5-9752-d5c0907c44da.jpg)

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
