### ISSUE TITLE
All the data are reflecting on the same page. No pagination available

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#68]
Log on into the application as School / OUP Admin and click on Utilities--> All the data are reflecting on the same page. No pagination available
![utilities](https://cloud.githubusercontent.com/assets/16289032/12232044/ef51d1f8-b881-11e5-92aa-fbbe84158725.jpg)

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
