### ISSUE TITLE
Side bar of OUP Admin doesn't not contain the Utilities option

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#69]
Log on into the application as OUP Admin and expand the side bar. Side bar of OUP Admin doest not contain the Utilities option
![side bar](https://cloud.githubusercontent.com/assets/16289032/12232095/478eb6ce-b882-11e5-8c21-81ff2186728a.jpg)

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
