### ISSUE TITLE
 Log on into the application as a OUP Admin and go to the school search page and search the created school. Click on the edit button of the school which will 

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#7]
Log on into the application as a OUP Admin and go to the school search page and search the created school. Click on the edit button of the school which will 
  take the user to the school edit page. Try to add a class code and subscription count on the "Classwise Subscription Details" section by clicking the "+"
  button. Click on the save button. The success message is displayed  with a "OK" button and "X" button to close the pop up. If the user clicks on the "OK" 
 button and again goes to the "Classwise Subscription Details" section and tries to delete the newly added subscription then it is getting deleted, however,
  if the user clicks on the "X" button of the message and tries to delete the newly added subscription then it throws an error message as attached in the 
 screenshot ( delete.jpg)
![delete](https://cloud.githubusercontent.com/assets/16289032/11924900/2324c0e6-a7dc-11e5-9847-b294386404a7.jpg)

**Comment by supriti-mukherjee** [comment]
Please check it once more.

**Comment by summar1** [comment]
Fixed
