### ISSUE TITLE
Mandatory field when left blank, and user tried to save the data, the field is not getting highlighted in red

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#71]
Log on into the application as School Admin and click on the profile link for school admin. In the profile page make fields blanks and click on save The Gender field which is a mandatory field is not highlighted in red

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Not Fixed

**Comment by supriti-mukherjee** [comment]
Fixed
