### ISSUE TITLE
Even if user has provided invalid input still the request is getting submitted and success message is thrown 

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#73]
From the home page click on the contact us link. Fill the contact details and email with invalid data and submit. The data is getting submitted successfully
![invalid data](https://cloud.githubusercontent.com/assets/16289032/12293496/f657cb94-ba19-11e5-8646-37f79d4143c0.jpg)

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
