### ISSUE TITLE
UI for the field can be modified

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#74]
From the home page click on the contact us link, the field to provide captcha  values, its UI can be modified a bit. “:” needs to be provided after “Input Symbols” and there should be some space between Input symbols and the text field
![ui](https://cloud.githubusercontent.com/assets/16289032/12293503/07d37a44-ba1a-11e5-90d7-8489294378df.jpg)

**Comment by supriti-mukherjee** [comment]
Its coming from Third party plugin. We already made possible customization to make UI better

**Comment by summar1** [comment]
ok
