### ISSUE TITLE
Salutation and name does not change. User has to log on again to view the updated data

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#78]
Log on into the application as OUP admin and click on my profile. Change the gender from male to female or vice versa, first name and last name and save the data. The salutation and the name doesn't change and still shows the old salutation and name. User has to log out and log in again to view the updated details.

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
