### ISSUE TITLE
Log on into the application as a OUP Admin and go to the school search page and search the created school. Click on the edit button of the school which will 

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#8]
Log on into the application as a OUP Admin and go to the school search page and search the created school. Click on the edit button of the school which will 
  take the user to the school edit page. Try to add a class code and subscription count on the "Classwise Subscription Details" section by clicking the "+"
  button. Click on the save button. The success message is displayed  with a "OK" button and "X" button to close the pop up. If the user clicks on the "OK" 
 button and again goes to the "Classwise Subscription Details" section and tries to add a class code and subscription then fields are shown distorted as 
 attached in the screenshot.(distorted.jpg)
![distorted](https://cloud.githubusercontent.com/assets/16289032/11924927/5cacd22c-a7dc-11e5-8cf8-22fce21aa509.jpg)

**Comment by supriti-mukherjee** [comment]
It is fixed and will be available on next deployment.

**Comment by summar1** [comment]
Fixed now
