### ISSUE TITLE
Logon into the application as OUp admin and search a school. try to edit the schools class and subscrition by clicking on the "+" button. Without filling any values for both the fields click on save. The error message thrown is not uniform

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#81]
Logon into the application as OUp admin and search a school. try to edit the schools class and subscrition by clicking on the "+" button. Without
filling any values for both the fields click on save. The error message thrown is not uniform
![save](https://cloud.githubusercontent.com/assets/16289032/12324296/a0d8549e-bae7-11e5-8ae4-866d93569f5e.jpg)

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
