### ISSUE TITLE
As per the FSD if the user has selected “service request” or others as option for “Request for” then message field should be a mandatory dropdown--> a “*” should be present against it if the user selects these two values from request for dropdown

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#83]
As per the FSD if the user has selected “service request” or others as option for “Request for” then message field should be a mandatory dropdown--> a “*” should be present against it if the user selects these two values from request for dropdown

**Comment by manasghosh81** [comment]
invalid

**Comment by supriti-mukherjee** [comment]
closed
