### ISSUE TITLE
OUP Admin--. Utilities/Advance search--> select a school and click on search. Search result is displayed. Now without reseting the value, fill the school code and again click on search. The Teacher grid is showing data which is common for the School and the school code selected.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#85]
OUP Admin--. Utilities/Advance search--> select a school and click on search. Search result is displayed. Now without reseting the value, fill the school code
and again click on search. The Teacher grid is showing data which is common for the School and the school code selected.

**Comment by supriti-mukherjee** [comment]
Its correct only

**Comment by summar1** [comment]
Fixed
