### ISSUE TITLE
OUP Admin--> Utilities--> search for some records. Now without selecting any data click on, print welcome letter or export selected link at the top. The message shown has a "no" button also which needs to be removed.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#88]
OUP Admin--> Utilities--> search for some records. Now without selecting any data click on, print welcome letter or export selected link at the top. The
message shown has a "no" button also which needs to be removed.

**Comment by supriti-mukherjee** [comment]
Fixed and closing on behalf of sonia.
