### ISSUE TITLE
On the home screen of OUP Mymaths homepage, the heading simplifying mathematics can be written on a single line.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#9]
On the home screen of OUP Mymaths homepage, the heading simplifying mathematics can be written on a single line.
   Also the "." can be removed from both "simplifying mathematics" & " the online way". (Aboutscreen_1.jpg)
![aboutscreen_1](https://cloud.githubusercontent.com/assets/16289032/11924942/83a179fa-a7dc-11e5-8fb3-56f80c17753b.jpg)

**Comment by supriti-mukherjee** [comment]
UI was discussed with client. "Simplifying Mathematics" will be in two lines.
Full stop we have removed and can be seen after next deployment.

**Comment by summar1** [comment]
Full stop is still there

**Comment by supriti-mukherjee** [comment]
can you share the screenshot?

**Comment by summar1** [comment]
Ok now
