### ISSUE TITLE
School Admin--> Create notification--> The notifications created for teacher(If there is no Teacher for the school) show success message for send/schedule but the notification history tab is not showing the data. Even if a notification is created for both teacher and student, then in the history grid the recepient is shown as student only

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#91]
School Admin--> Create notification--> The notifications created for teacher(If there is no Teacher for the school) show success message for send/schedule but the notification history tab
is not showing the data. Even if a notification is created for both teacher and student, then in the history grid the recepient is shown as student only

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
fixed
