### ISSUE TITLE
School Admin/OUP Admin--> create some notificcation so that history grid should have atleasst 2 pages.now go to the second page and delete one notification from there The notification is deleted successfully from the history grid also . Come back to page 1 and again revisit page 2. The deleted notification will be avaiable again User can do this for any notification on any page

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#92]
School Admin/OUP Admin--> create some notificcation so that history grid should have atleasst 2 pages.now go to the second page and delete one notification from there
The notification is deleted successfully from the history grid also . Come back to page 1 and again revisit page 2. The deleted notification will be avaiable again
User can do this for any notification on any page

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
