### ISSUE TITLE
OUPADMIN--> Advance search--> try to do a search based on school name. This drop down shows the school name in the order in which it has been created. can it be sorted alphabatically

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#93]
OUPADMIN--> Advance search--> try to do a search based on school name. This drop down shows the school name in the order in which it has been created.
can it be sorted alphabatically

**Comment by supriti-mukherjee** [comment]
It is not an issue as per discussion.

**Comment by summar1** [comment]
Changed to enhancement

**Comment by mouparnadas** [comment]
This has been added. Please test.

**Comment by summar1** [comment]
fixed now
