### ISSUE TITLE
Class--> seclect a class from the dropdown and click on Go. Select any section and view students. The student details is generated at the bottom in a  grid. Now Click on the "Add section" at the top. A new section is added successfully but the details of students in the grid is removed and there is a message Stating "No data available in table"

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#97]
Class--> seclect a class from the dropdown and click on Go. Select any section and view students. The student details is generated at the bottom in a 
grid. Now Click on the "Add section" at the top. A new section is added successfully but the details of students in the grid is removed and there is a message
Stating "No data available in table"

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
