### ISSUE TITLE
Notification history search grid is becoming distorted when user clicks on teh sorting option of "send date", "School Name" and "Subject" column.

### ISSUE THREAD

**Issue by summar1** [manasghosh81/MyMathsTesting#99]
create notification. In the History tab , previously created notification is shown. Notification history search grid is becoming distorted when user clicks on the sorting option of "send date", "School Name" and "Subject" column.

**Comment by supriti-mukherjee** [comment]
Fixed

**Comment by summar1** [comment]
Fixed
